<a href="https://colab.research.google.com/github/justmexmehak/DeepLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors
Ctrl + MB for new cell

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor - ndim
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([
    [10, 7],
    [73, 37]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [73, 37]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2 = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.]
], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
tensor = tf.constant([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [7, 8, 9],
      [3, 2, 1]
    ],
    [
      [4, 3, 4],
      [3, 7, 3]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 2, 1]],

       [[4, 3, 4],
        [3, 7, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Tensor - an n-dimensional array of numbers

### Creating tensors with tf.Variable

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
changeable_tensor[0].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>

### Random tensors
 Neural networks initializes itself with random weights (random tensor)
 Looks at the input examples learns and updates itself to match the input

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
# shuffle a tensor (to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffles a tensor along it's first dimension
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# without any seed gives different result each time
# with a global level seed set gives the same result
# tf.random.set_seed(12)
# with an operation level seed gives a different result
tf.random.shuffle([
    [1, 2, 3, 4],
    [3, 7, 7, 3],
    [1, 2, 2, 1]
], seed=12
)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[3, 7, 7, 3],
       [1, 2, 2, 1],
       [1, 2, 3, 4]], dtype=int32)>

According to the documentation,
https://www.tensorflow.org/api_docs/python/tf/random/set_seed#:~:text=Operations%20that%20rely%20on%20a,is%20used%20for%20this%20op.,
If neither op level and global level seed are set a random seed is picked for the operation.
If global seed is set, but op seed is not, system deterministically picks an op seed in conjuntion with the global seed to generate a unique random sequence. (we get different results for every call to the random op but the same sequence for every re-run of the program)
If op seed is set, and global is not, a default global seed and specified op seed are used.
If both are set, both are used in conjuction to determine random sequence.

### Other ways to make tensors

In [ ]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(( 10, 10), tf.int32)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run much faster on a GPU for numerical computing

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

A = tf.constant(numpy_A, shape=(2, 3, 4)) # shape must have same no. el as in og array 2 * 3 * 4 = 24
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting Information from Tensors

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
A.shape

TensorShape([2, 3, 4])

In [ ]:
A.ndim # rank

3

In [ ]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor.ndim

4

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Axis or Dimension
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


In [ ]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

### Indexing Tensors

In [ ]:
# Get the first 2 elements of each dimension of tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1 , :]
# Except for the first dimension
rank_4_tensor[:, :1, :1 , :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10, 7], [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get last element of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
# rank_2_tensor[..., tf.newaxis] is same as rank_2_tensor[:, :, tf.newaxis]
# the ... notation means on every previous axis
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors (Tensor Operations)

In [ ]:
# does not manipulate the og tensor
tensor = rank_2_tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

In [ ]:
tensor * 10
tensor // 10
tensor / 10
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# built in tensorflow function
# tf.multiply() is alias of tf.math.multiply()
# typically the built in functions are faster when running on GPU
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[300, 270],
       [230, 240]], dtype=int32)>

### Matrix Multiplication

row1 x col1 row2 x col2

col1 must be equal to row 2

The resulting matrix will have the dimensions row1 x col2

In [ ]:
# tf.linalg.matmul
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[30 27]
 [23 24]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1521, 1458],
       [1242, 1197]], dtype=int32)>

In [ ]:
# element wise multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[900, 729],
       [529, 576]], dtype=int32)>

In [ ]:
t1 = tf.constant([
    [1, 2, 5],
    [7, 2, 1],
    [3, 3, 3]
])
t2 = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])
tf.matmul(t1, t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# @ is python op for matrix multiplication
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>